# Generated by Django 4.2 on 2023-04-22 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('hackathon_image', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reward_prize', models.CharField(default=None, max_length=255)),
            ],
            options={
                'verbose_name': 'hackathon',
                'verbose_name_plural': 'hackathons',
                'db_table': 'hackathons',
            },
        ),
    ]
