# Generated by Django 4.2 on 2023-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='reward_prize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
