# Generated by Django 4.2 on 2023-04-22 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
        ('hackathons', '0002_alter_hackathon_reward_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Hackathon Register',
                'verbose_name_plural': 'Hackathon Registers',
                'db_table': 'hackathon_registers',
            },
        ),
    ]
