# Generated by Django 4.2 on 2023-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_hackathonregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='submission_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('FILE', 'File'), ('LINK', 'Link')], default='LINK', max_length=20),
        ),
    ]
