# Generated by Django 4.2 on 2023-04-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
        ('hackathons', '0004_hackathon_submission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rel', to='users.user'),
        ),
    ]
