# Generated by Django 4.2 on 2023-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
